# Site settings
title: Producera och leverera mjukvaror
subtitle: Software craftmanship
description: |
    För att kunna jobba som systemutvecklare, räcker det inte att enbart känna till hur man skriver kod och dom verktyg man använder, 
    man måste också ha en djup kunskap om dom processor och verktyg som man använder båda utvecklingsprocessen 
    och hur man leverera mjukvaror till slut användaren.
baseurl: "/course-producera-leverera" # the subpath of your site, e.g. /blog/
url: "http://PGBSNH19.github.io/course-producera-leverera" # the base hostname & protocol for your site
githubdir: "PGBSNH19/course-producera-leverera"
lms-name: Ping Ping
lms-url: https://yh.pingpong.se/courseId/11988/content.do?id=4841787
course-start: 2020-12-07
course-end: 2021-01-22
timezone: Europe/Stockholm


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
